module.exports = {
    'Core': [
      {
        type: 'autogenerated',
        dirName: 'core'
      }
    ],
    'Exchange': [
      {
        type: 'autogenerated',
        dirName: 'exchange'
      }
    ]
  }